# This workflow releases the project on Maven Central
# and prepare a new development version

name: Release

on:
  #push:
  #  branches: [ main ]
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Release version"
        required: true
        default: ""
      developmentVersion:
        description: "New version in development (with SNAPSHOT)"
        required: true
        default: ""

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK with Maven Central Repository
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        java-package: 'jdk'
        cache: 'maven'
        server-id: ossrh
    - name: Configure Git User
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
    - name: Import GPG Key
      uses: crazy-max/ghaction-import-gpg@v5.0.0
      with:
        gpg_private_key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
    - name: Create release branch
      run: |
        git checkout release/${{ github.event.inputs.releaseVersion }} 2>/dev/null || git checkout -b release/${{ github.event.inputs.releaseVersion }}
    - name: Clean up existing release tags
      run: |
        git tag -d v${{ github.event.inputs.releaseVersion }} || true
        git push origin :refs/tags/v${{ github.event.inputs.releaseVersion }} || true
    - name: Prepare release with Maven
      id: prepare
      run: |
        mvn -B -U \
          -Prelease \
          release:clean \
          release:prepare \
          -s settings.xml \
          -Dgpg.passphrase=${{ secrets.MAVEN_GPG_PASSPHRASE }} \
          -DreleaseVersion=${{ github.event.inputs.releaseVersion }} \
          -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }} \
          -Dresume=false
    - name: Release rollback because prepation failed
      run: |
        mvn -B -U \
          -Prelease \
          release:rollback \
          -s settings.xml
      if: always() && (steps.prepare.outcome == 'failure')
    - name: Release With Maven
      run: |
        mvn -B -U \
          -Prelease \
          release:perform \
          -s settings.xml \
          -Dgpg.passphrase=${{ secrets.MAVEN_GPG_PASSPHRASE }} \
          -DreleaseVersion=${{ github.event.inputs.releaseVersion }} \
          -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }} \
          deploy
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        AUTO_RELEASE_AFTER_CLOSE: ${{ env.auto_release }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        title: Release v${{ github.event.inputs.releaseVersion }} and prepare v${{ github.event.inputs.developmentVersion }}
        body: |
          Automated release
          - Release v${{ github.event.inputs.releaseVersion }} 
          - Prepare v${{ github.event.inputs.developmentVersion }}
